name: Generate Snake Animation

on:
  schedule:
    # Se ejecuta automáticamente cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Genera los archivos SVG animando el mapa de contribuciones
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Guarda y hace commit automático de las imágenes generadas en la carpeta assets
      - name: Commit and Push Assets
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add assets/
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update contribution snake animation"
          git push
